name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean Workspace
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Force Inject V2 Embedding
        run: |
          # Memaksa penghapusan tag lama (jika ada) untuk menghindari duplikasi
          sed -i '/android:name="flutterEmbedding"/d' android/app/src/main/AndroidManifest.xml
          # Menginjeksi tag V2 tepat di bawah elemen <application>
          sed -i '/<application/a \        <meta-data android:name="flutterEmbedding" android:value="2" />' android/app/src/main/AndroidManifest.xml
          # Menampilkan isi file ke log Actions untuk verifikasi visual
          echo "=== ISI ANDROID MANIFEST SAAT INI ==="
          cat android/app/src/main/AndroidManifest.xml

      - name: Build APK Release
        run: flutter build apk --release -v
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-interactive-release
          path: build/app/outputs/flutter-apk/app-release.apk
